apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - name: grafanaport
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: grafana-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: GRAFANA_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: grafana_port
        - name: INFLUX_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: influx_port
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: influx_user
        - name: INFLUX_PASW
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: influx_pasw
        - name: GRAFANA_USER
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: grafana_user
        - name: GRAFANA_PASW
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: grafana_pasw
