apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - name: mysqlport
    port: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: mysql_port
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: mysql_user
        - name: MYSQL_PASW
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: mysql_pasw
        volumeMounts:
        - name: mysql-db
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-db
        persistentVolumeClaim:
          claimName: mysql-volume
