apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - name: pmaport
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          tcpSocket:
            port: 5000
        env:
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: mysql_port
        - name: PMA_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: pma_port
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: mysql_user
        - name: MYSQL_PASW
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: mysql_pasw
