apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf-container
        image: telegraf-image
        imagePullPolicy: Never
        env:
        - name: INFLUX_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: influx_port
        - name: INFLUX_USER
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: influx_user
        - name: INFLUX_PASW
          valueFrom:
            secretKeyRef:
              name: global-secret
              key: influx_pasw
        volumeMounts:
        - name: telegraf-socket
          mountPath: /var/run/docker.sock/
      volumes:
      - name: telegraf-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
